//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to check your SPAM-box. The e-mail could end up there ;).
        /// </summary>
        internal static string CheckInbox {
            get {
                return ResourceManager.GetString("CheckInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to check your SPAM-box. It should be empty, since no mail is sent ;).
        /// </summary>
        internal static string CheckSpamBox {
            get {
                return ResourceManager.GetString("CheckSpamBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sample.
        /// </summary>
        internal static string CodeSample {
            get {
                return ResourceManager.GetString("CodeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a controller class, access the extension methods by using &quot;this.&quot;, as such:.
        /// </summary>
        internal static string ControllerExtensions_MethodDescription {
            get {
                return ResourceManager.GetString("ControllerExtensions_MethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In test context, use the CallWithModelValidation method to automatically apply model validation when calling an action that requires it. By default, model validation is not applied, which causes model errors to be ignored by unit tests..
        /// </summary>
        internal static string ControllerExtensions_Testing_MethodDescription {
            get {
                return ResourceManager.GetString("ControllerExtensions_Testing_MethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The week methods can also be adjusted to support ISO8601, localization etc. but that is left out of this demo..
        /// </summary>
        internal static string DateTimeExtensions_WeekComment {
            get {
                return ResourceManager.GetString("DateTimeExtensions_WeekComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation output.
        /// </summary>
        internal static string DocumentationOutput {
            get {
                return ResourceManager.GetString("DocumentationOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to demo@nextra.
        /// </summary>
        internal static string EmailFromMail {
            get {
                return ResourceManager.GetString("EmailFromMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Extensions.
        /// </summary>
        internal static string EmailFromName {
            get {
                return ResourceManager.GetString("EmailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail should not be sent.
        /// </summary>
        internal static string EmailNonSenderBody {
            get {
                return ResourceManager.GetString("EmailNonSenderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing EmailNonSender.
        /// </summary>
        internal static string EmailNonSenderSubject {
            get {
                return ResourceManager.GetString("EmailNonSenderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail should be sent.
        /// </summary>
        internal static string EmailSenderBody {
            get {
                return ResourceManager.GetString("EmailSenderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing EmailSender.
        /// </summary>
        internal static string EmailSenderSubject {
            get {
                return ResourceManager.GetString("EmailSenderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a double-valued angle in either degrees or radians to convert it.
        /// </summary>
        internal static string EnterAngleToConvert {
            get {
                return ResourceManager.GetString("EnterAngleToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter cookie name.
        /// </summary>
        internal static string EnterCookieName {
            get {
                return ResourceManager.GetString("EnterCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a cookie name and an optional value (no value =&gt; no set).
        /// </summary>
        internal static string EnterCookieNameAndValue {
            get {
                return ResourceManager.GetString("EnterCookieNameAndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter cookie value.
        /// </summary>
        internal static string EnterCookieValue {
            get {
                return ResourceManager.GetString("EnterCookieValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a date to apply available extension methods on it.
        /// </summary>
        internal static string EnterDateTimeToExtend {
            get {
                return ResourceManager.GetString("EnterDateTimeToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a distance in either kilometers or miles to convert it.
        /// </summary>
        internal static string EnterDistanceToConvert {
            get {
                return ResourceManager.GetString("EnterDistanceToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a file size.
        /// </summary>
        internal static string EnterFileSize {
            get {
                return ResourceManager.GetString("EnterFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a file size (in bytes) to present it in a readable fashion.
        /// </summary>
        internal static string EnterFileSizeAndFormat {
            get {
                return ResourceManager.GetString("EnterFileSizeAndFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a file URL.
        /// </summary>
        internal static string EnterFileUrl {
            get {
                return ResourceManager.GetString("EnterFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a file URL to load the file via the facade class..
        /// </summary>
        internal static string EnterFileUrlToLoad {
            get {
                return ResourceManager.GetString("EnterFileUrlToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string to convert any HTML5 content within it.
        /// </summary>
        internal static string EnterHtml5StringToConvert {
            get {
                return ResourceManager.GetString("EnterHtml5StringToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a latitude.
        /// </summary>
        internal static string EnterLatitude {
            get {
                return ResourceManager.GetString("EnterLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a latitude and longitude to create a Position instance.
        /// </summary>
        internal static string EnterLatitudeAndLongitudeToCreatePosition {
            get {
                return ResourceManager.GetString("EnterLatitudeAndLongitudeToCreatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter two latitudes and longitudes to handle the positions.
        /// </summary>
        internal static string EnterLatitudeAndLongitudeToHandlePositions {
            get {
                return ResourceManager.GetString("EnterLatitudeAndLongitudeToHandlePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value to limit.
        /// </summary>
        internal static string EnterLimitValue {
            get {
                return ResourceManager.GetString("EnterLimitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a longitude.
        /// </summary>
        internal static string EnterLongitude {
            get {
                return ResourceManager.GetString("EnterLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a max value.
        /// </summary>
        internal static string EnterMaxValue {
            get {
                return ResourceManager.GetString("EnterMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a min value.
        /// </summary>
        internal static string EnterMinValue {
            get {
                return ResourceManager.GetString("EnterMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number format.
        /// </summary>
        internal static string EnterNumberFormat {
            get {
                return ResourceManager.GetString("EnterNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a numerical value to apply available extension methods on it.
        /// </summary>
        internal static string EnterNumericalToExtend {
            get {
                return ResourceManager.GetString("EnterNumericalToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a regex pattern.
        /// </summary>
        internal static string EnterPattern {
            get {
                return ResourceManager.GetString("EnterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a regex pattern and a value to validate the value with the attribute.
        /// </summary>
        internal static string EnterPatternAndValueToValidate {
            get {
                return ResourceManager.GetString("EnterPatternAndValueToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string.
        /// </summary>
        internal static string EnterString {
            get {
                return ResourceManager.GetString("EnterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string to add it to a StateBag instance and access it strongly typed.
        /// </summary>
        internal static string EnterStringToAddToStateBag {
            get {
                return ResourceManager.GetString("EnterStringToAddToStateBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string to apply available extension methods on it.
        /// </summary>
        internal static string EnterStringToExtend {
            get {
                return ResourceManager.GetString("EnterStringToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string to hash.
        /// </summary>
        internal static string EnterStringToHash {
            get {
                return ResourceManager.GetString("EnterStringToHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid RSS feed URL (like the one that is used by default) to load the feed with the syndication feed loader.
        ///
        ///To inspect the result (which is ust presented as a JSON object), just copy the string into a text editor..
        /// </summary>
        internal static string EnterStringToLoadFeed {
            get {
                return ResourceManager.GetString("EnterStringToLoadFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid file URL (like the one that is used by default) to load the file with the virtual file handler..
        /// </summary>
        internal static string EnterStringToLoadFile {
            get {
                return ResourceManager.GetString("EnterStringToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter two values to apply extension methods to a resulting key-value pair.
        /// </summary>
        internal static string EnterTwoValuesToExtendObject {
            get {
                return ResourceManager.GetString("EnterTwoValuesToExtendObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter two values to serialize a string list with JSON.
        /// </summary>
        internal static string EnterTwoValuesToJson {
            get {
                return ResourceManager.GetString("EnterTwoValuesToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a URI to apply available extension methods on it.
        /// </summary>
        internal static string EnterUriToExtend {
            get {
                return ResourceManager.GetString("EnterUriToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value.
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current action uses an JsonForQueryStringAttribute that requires that the query variable &quot;value&quot; has the value &quot;json&quot;. Enter &quot;json&quot; in the text box to try it out:.
        /// </summary>
        internal static string EnterValueToAffectOutput {
            get {
                return ResourceManager.GetString("EnterValueToAffectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string to add it to a StringCollection.
        /// </summary>
        internal static string EnterValueToExtendedCollection {
            get {
                return ResourceManager.GetString("EnterValueToExtendedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value to hash it.
        /// </summary>
        internal static string EnterValueToHash {
            get {
                return ResourceManager.GetString("EnterValueToHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to send an e-mail.
        /// </summary>
        internal static string EnterValueToSendEmail {
            get {
                return ResourceManager.GetString("EnterValueToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to simulate sending an e-mail.
        /// </summary>
        internal static string EnterValueToSimulateEmail {
            get {
                return ResourceManager.GetString("EnterValueToSimulateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value in the box below, to validate it with the attribute.
        /// </summary>
        internal static string EnterValueToValidate {
            get {
                return ResourceManager.GetString("EnterValueToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value to wrap it in an EventArgs instance.
        /// </summary>
        internal static string EnterValueToWrapInEventArgs {
            get {
                return ResourceManager.GetString("EnterValueToWrapInEventArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value to wrap it in a Nullable instance.
        /// </summary>
        internal static string EnterValueToWrapInNullable {
            get {
                return ResourceManager.GetString("EnterValueToWrapInNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address.
        /// </summary>
        internal static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class is a generic version of the native EventArgs class. It embeds an object that can be accessed within a raised event..
        /// </summary>
        internal static string EventArgs_TypeSummary {
            get {
                return ResourceManager.GetString("EventArgs_TypeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class can wrap any base class and expose it as a property..
        /// </summary>
        internal static string FacadeBase_TypeSummary {
            get {
                return ResourceManager.GetString("FacadeBase_TypeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate hash value.
        /// </summary>
        internal static string GenerateHash {
            get {
                return ResourceManager.GetString("GenerateHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the site styles, nav is green and .nav is red. So, if the box below is green, you are viewing HTML5. If not, you&apos;re a HTML4 kind o&apos; person..
        /// </summary>
        internal static string Html5ElementConvertModuleDescription1 {
            get {
                return ResourceManager.GetString("Html5ElementConvertModuleDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a look in the web.config file to see how the module is applied for the site..
        /// </summary>
        internal static string Html5ElementConvertModuleDescription2 {
            get {
                return ResourceManager.GetString("Html5ElementConvertModuleDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit can be used to limit any IComparable (here, String) between two values.
        /// </summary>
        internal static string IComparableExtensions_LimitDescription {
            get {
                return ResourceManager.GetString("IComparableExtensions_LimitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paginate can be used to Skip and Take in one step. The various OrderBy and ThenBy methods can be used to sort collections by property name.
        /// </summary>
        internal static string IEnumerableExtensions_MethodDescriptions {
            get {
                return ResourceManager.GetString("IEnumerableExtensions_MethodDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paginate can be used to Skip and Take in one step. The various OrderBy and ThenBy methods can be used to sort collections by property name.
        /// </summary>
        internal static string IQueryableExtensions_MethodDescriptions {
            get {
                return ResourceManager.GetString("IQueryableExtensions_MethodDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items per page.
        /// </summary>
        internal static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load assembly.
        /// </summary>
        internal static string LoadAssembly {
            get {
                return ResourceManager.GetString("LoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load documentation for a .NET Extensions assembly.
        /// </summary>
        internal static string LoadAssemblyDocumentation {
            get {
                return ResourceManager.GetString("LoadAssemblyDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load documentation for any member of the current view model class.
        /// </summary>
        internal static string LoadMemberInfoDocumentation {
            get {
                return ResourceManager.GetString("LoadMemberInfoDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load documentation for any method in the current view model class.
        /// </summary>
        internal static string LoadMethodInfoDocumentation {
            get {
                return ResourceManager.GetString("LoadMethodInfoDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load documentation for the current view model class (DemoModel).
        /// </summary>
        internal static string LoadTypeDocumentation {
            get {
                return ResourceManager.GetString("LoadTypeDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Extensions.
        /// </summary>
        internal static string NExtra {
            get {
                return ResourceManager.GetString("NExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documentation is specified for the selected member.
        /// </summary>
        internal static string NotDocumentedMember {
            get {
                return ResourceManager.GetString("NotDocumentedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documentation is specified for the selected method.
        /// </summary>
        internal static string NotDocumentedMethod {
            get {
                return ResourceManager.GetString("NotDocumentedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documentation is specified for the selected type.
        /// </summary>
        internal static string NotDocumentedType {
            get {
                return ResourceManager.GetString("NotDocumentedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class can be used to make non-nullable reference types behave like nullable reference types, such as int? and bool?.
        /// </summary>
        internal static string Nullable_TypeSummary {
            get {
                return ResourceManager.GetString("Nullable_TypeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page links.
        /// </summary>
        internal static string PageLinks {
            get {
                return ResourceManager.GetString("PageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class can handle the pagination for any IEnumerable or IQueryable collection. It can calculate the number of pages for collection, given a certain page size, and can also determine how it can be paginated, according to the current page number..
        /// </summary>
        internal static string PaginationContext_TypeSummary {
            get {
                return ResourceManager.GetString("PaginationContext_TypeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Select assembly ===.
        /// </summary>
        internal static string SelectAssembly {
            get {
                return ResourceManager.GetString("SelectAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an assembly to apply available extension methods on it.
        /// </summary>
        internal static string SelectAssemblyToExtend {
            get {
                return ResourceManager.GetString("SelectAssemblyToExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Select member ===.
        /// </summary>
        internal static string SelectMember {
            get {
                return ResourceManager.GetString("SelectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Select method ===.
        /// </summary>
        internal static string SelectMethod {
            get {
                return ResourceManager.GetString("SelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as message.
        /// </summary>
        internal static string SendEmailWithMessage {
            get {
                return ResourceManager.GetString("SendEmailWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send with params.
        /// </summary>
        internal static string SendEmailWithParameters {
            get {
                return ResourceManager.GetString("SendEmailWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show max.
        /// </summary>
        internal static string ShowMax {
            get {
                return ResourceManager.GetString("ShowMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class can not be demoed here. Download the source code to see examples..
        /// </summary>
        internal static string TestClassNotDemoed {
            get {
                return ResourceManager.GetString("TestClassNotDemoed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then by.
        /// </summary>
        internal static string ThenBy {
            get {
                return ResourceManager.GetString("ThenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the original source, this is a nav element.
        /// </summary>
        internal static string ThisIsANav {
            get {
                return ResourceManager.GetString("ThisIsANav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it out.
        /// </summary>
        internal static string TryItOut {
            get {
                return ResourceManager.GetString("TryItOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using the view model class.
        /// </summary>
        internal static string UsingTheViewModelClass {
            get {
                return ResourceManager.GetString("UsingTheViewModelClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For methods and constructors, this demo will only retrieve documentation for the parameterless ones.  This is just due to laziness :).
        /// </summary>
        internal static string XmlDocumentationHandlerComment {
            get {
                return ResourceManager.GetString("XmlDocumentationHandlerComment", resourceCulture);
            }
        }
    }
}
