using System;
using System.IO;
using System.Text;
using System.Web;
using NExtra.Web.Abstractions;

namespace NExtra.Web.ResponseFilters
{
    /// <summary>
    /// This filter can be used to automatically convert all HTML5
    /// elements withinin the client response to HTML4 elements if
    /// the current browser does not support HTML5 elements.
    /// 
    /// To use the filter, apply it to the current response filter
    /// in global.asax, or using the Html5ElementConvertHttpModule.
    /// This filter will ONLY convert HTML5 elements if the output
    /// is generated by a Page or an MvcHandler and if the context
    /// does not support HTML5.
    /// </summary>
    /// <remarks>
    /// Author:     Daniel Saidi [daniel.saidi@gmail.com]
    /// Link:       http://www.saidi.se/nextra
    /// </remarks>
    public class Html5ElementConvertFilter : Stream
    {
        private readonly Stream baseStream;
        private readonly StringBuilder html;
        private readonly ICanDetermineHtml5ElementSupport html5ElementSupport;
        private readonly ICanConvertHtml htmlConverter;
        private bool isFlushed;


        /// <summary>
        /// Create an instance of the class.
        /// </summary>
        /// <param name="baseStream">The stream to filter.</param>
        public Html5ElementConvertFilter(Stream baseStream)
            : this(baseStream, new Html5ElementSupport(), new Html5ElementConverter())
        { }

        /// <summary>
        /// Create an instance of the class that uses custom
        /// implementations of ICanDetermineHtml5Support and
        /// ICanConvertHtml5Elements.
        /// </summary>
        /// <param name="baseStream">The stream to filter.</param>
        /// <param name="html5ElementSupport">The ICanDetermineHtml5Support implementation to use.</param>
        /// <param name="htmlConverter">The ICanConvertHtml5Elements implementation to use.</param>
        public Html5ElementConvertFilter(Stream baseStream, ICanDetermineHtml5ElementSupport html5ElementSupport, ICanConvertHtml htmlConverter)
        {
            this.baseStream = baseStream;
            html = new StringBuilder();
            this.html5ElementSupport = html5ElementSupport;
            this.htmlConverter = htmlConverter;
        }


        /// <summary>
        /// Whether or not to convert HTML5 elements.
        /// </summary>
        /// <remarks>
        /// Only convert HTML5 elements if the handler is a page or an MVC
        /// handler and ONLY if the current browser does not support HTML5.
        /// </remarks>
        private bool ConversionEnabled
        {
            get
            {
                //var isPage = (HttpContext.Current.Handler as Page) != null;
                //var isMvc = (HttpContext.Current.Handler as MvcHandler) != null;
                var isHtml = HttpContext.Current.Response.ContentType == "text/html";
                var hasHtml5Support = html5ElementSupport.HasHtml5ElementSupport(HttpContext.Current);

                return /*(isPage || isMvc) && */isHtml && !hasHtml5Support;
            }
        }


        /// <summary>
        /// Flush the generated output. This will write the resulting HTML
        /// code to the base stream and flush the stream.
        /// </summary>
        public override void Flush()
        {
            if (!ConversionEnabled || isFlushed)
                return;

            using (var writer = new StreamWriter(baseStream))
            {
                writer.Write(htmlConverter.ConvertHtml(html.ToString()));
            }

            baseStream.Flush();
            isFlushed = true;
        }

        /// <summary>
        /// Write buffer to the temp HTML string.  
        /// </summary>
        public override void Write(byte[] buffer, int offset, int count)
        {
            if (!ConversionEnabled)
            {
                baseStream.Write(buffer, offset, count);
                return;
            }

            html.Append(HttpContext.Current.Response.ContentEncoding.GetString(buffer, offset, count));
        }


        /// <summary>
        /// Always returns false.
        /// </summary>
        public override bool CanRead { get { return false; } }

        /// <summary>
        /// Always returns false.
        /// </summary>
        public override bool CanSeek { get { return false; } }

        /// <summary>
        /// Always returns true.
        /// </summary>
        public override bool CanWrite { get { return true; } }

        /// <summary>
        /// Not implemented.
        /// </summary>
        public override long Length { get { throw new NotImplementedException(); } }

        /// <summary>
        /// Not implemented.
        /// </summary>
        public override long Position { get { throw new NotImplementedException(); } set { throw new NotImplementedException(); } }

        /// <summary>
        /// Not implemented.
        /// </summary>
        public override int Read(byte[] buffer, int offset, int count) { throw new NotImplementedException(); }

        /// <summary>
        /// Not implemented.
        /// </summary>
        public override long Seek(long offset, SeekOrigin origin) { throw new NotImplementedException(); }

        /// <summary>
        /// Not implemented.
        /// </summary>
        public override void SetLength(long value) { throw new NotImplementedException(); }
    }
}
